"""empty message

Revision ID: 19467925a5a4
Revises: 75a53690ff56
Create Date: 2022-05-06 04:52:26.369159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19467925a5a4'
down_revision = '75a53690ff56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role', type_=sa.Integer,
                    postgresql_using='role::int')
    op.alter_column('groups', 'title', type_=sa.Integer,
                    postgresql_using='title::int')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
