"""empty message

Revision ID: 2517e6aecb13
Revises: 
Create Date: 2022-05-06 04:15:40.609877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2517e6aecb13'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_groups_title'), 'groups', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_groups_title'), table_name='groups')
    # ### end Alembic commands ###
