"""users_to_answers; answer в question

Revision ID: ee1ab7073f82
Revises: f4472992a3ec
Create Date: 2022-05-10 05:45:30.925498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee1ab7073f82'
down_revision = 'f4472992a3ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_to_answers',
    sa.Column('users', sa.Integer(), nullable=True),
    sa.Column('answers', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['answers'], ['answers.id'], ),
    sa.ForeignKeyConstraint(['users'], ['users.id'], )
    )
    op.add_column('questions', sa.Column('answer', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'answer')
    op.drop_table('users_to_answers')
    # ### end Alembic commands ###
